### ISSUE TITLE
能否使用 Code interpreter 记录回答的花费时间？

### ISSUE THREAD

**Issue by HeroBlackInk** [hubeiqiao/IELTS-Speaking-Simulator#2]
这是一个非常有创意，有价值的App。对于我和那些需要练习雅思口语的人们带来了极大的便利。非常感谢作者的贡献。

我提一个小的改进，不知道实现起来难度如何？

在每次对话的提问过程中，能否使用 Code interpreter 记录考生的回答花费了多长时间？

**Comment by hubeiqiao** [comment]
目前 ChatGPT 官方应用有语音对话的总时长，您是想知道每个 话题/问题 分别用了多长时间？比如 Part 2 想尽量到 2 分钟之类的？

**Comment by hubeiqiao** [comment]
> 这是一个非常有创意，有价值的App。对于我和那些需要练习雅思口语的人们带来了极大的便利。非常感谢作者的贡献。
> 
> 我提一个小的改进，不知道实现起来难度如何？
> 
> 在每次对话的提问过程中，能否使用 Code interpreter 记录考生的回答花费了多长时间？

目前 ChatGPT 官方应用有语音对话的总时长，您是想知道每个 话题/问题 分别用了多长时间？比如 Part 2 想尽量到 2 分钟之类的？

**Comment by HeroBlackInk** [comment]
是的，可以观察自己回答是否超时。

**Comment by hubeiqiao** [comment]
> 是的，可以观察自己回答是否超时。

理论上可以加，但是加了后由于 Code Interpreter 运行的不稳定（如果你多次使用就会发现随机抽题时也并不稳定），体验一定会变差。因此，目前在这个上面不会添加该功能。你可以复制一份调整 Prompt 试试。

但我觉得要做到实际可用，需要单独用 API 来完整产品化实现。或者等 OpenAI 的迭代。
