### ISSUE TITLE
IELTS Writing Mentor支持OpenAI的api使用吗

### ISSUE THREAD

**Issue by baizhougod** [hubeiqiao/IELTS-Speaking-Simulator#6]
我知道原生api不支持gpts，如果提供prompt是不是可以实现和网页使用一样的效果

**Comment by hubeiqiao** [comment]
如果涉及到语音交互，至少目前还是不一样的。要实现类似 ChatGPT 的语音交互还是需要耗费大量资源的。

**Comment by baizhougod** [comment]
> 如果涉及到语音交互，至少目前还是不一样的。要实现类似 ChatGPT 的语音交互还是需要耗费大量资源的。

我的api渠道4o 1分(CNY) 1k token，应该比每月20$便宜，就是语音对话没有解决，是不是靠prompt可以实现Writing Mentor的体验，就是speak赶不上

**Comment by hubeiqiao** [comment]
> > 如果涉及到语音交互，至少目前还是不一样的。要实现类似 ChatGPT 的语音交互还是需要耗费大量资源的。
> 
> 我的api渠道4o 1分(CNY) 1k token，应该比每月20$便宜，就是语音对话没有解决，是不是靠prompt可以实现Writing Mentor的体验，就是speak赶不上

Writing 和 Reading 可以直接用 Prompt 实现，语音不行。以及马上实时语音对话就要来了（希望 8 月能够被灰度到 = =！），开 ChatGPT Plus 还是值得的。

**Comment by baizhougod** [comment]
> > > 如果涉及到语音交互，至少目前还是不一样的。要实现类似 ChatGPT 的语音交互还是需要耗费大量资源的。
> > 
> > 
> > 我的api渠道4o 1分(CNY) 1k token，应该比每月20$便宜，就是语音对话没有解决，是不是靠prompt可以实现Writing Mentor的体验，就是speak赶不上
> 
> Writing 和 Reading 可以直接用 Prompt 实现，语音不行。以及马上实时语音对话就要来了（希望 8 月能够被灰度到 = =！），开 ChatGPT Plus 还是值得的。



> > > 如果涉及到语音交互，至少目前还是不一样的。要实现类似 ChatGPT 的语音交互还是需要耗费大量资源的。
> > 
> > 
> > 我的api渠道4o 1分(CNY) 1k token，应该比每月20$便宜，就是语音对话没有解决，是不是靠prompt可以实现Writing Mentor的体验，就是speak赶不上
> 
> Writing 和 Reading 可以直接用 Prompt 实现，语音不行。以及马上实时语音对话就要来了（希望 8 月能够被灰度到 = =！），开 ChatGPT Plus 还是值得的。

那Writing 和 Reading 的 Prompt 能分享一下嘛，国产的海螺ai好像语音不错，能力怎么样还没试，抽题是部署在cf上面嘛，这个能不能通过大段prompt实现，或者自行部署啥的，感觉公用还是不稳定，要请求几次

**Comment by hubeiqiao** [comment]
> > > > 如果涉及到语音交互，至少目前还是不一样的。要实现类似 ChatGPT 的语音交互还是需要耗费大量资源的。
> > > 
> > > 
> > > 我的api渠道4o 1分(CNY) 1k token，应该比每月20$便宜，就是语音对话没有解决，是不是靠prompt可以实现Writing Mentor的体验，就是speak赶不上
> > 
> > 
> > Writing 和 Reading 可以直接用 Prompt 实现，语音不行。以及马上实时语音对话就要来了（希望 8 月能够被灰度到 = =！），开 ChatGPT Plus 还是值得的。
> 
> > > > 如果涉及到语音交互，至少目前还是不一样的。要实现类似 ChatGPT 的语音交互还是需要耗费大量资源的。
> > > 
> > > 
> > > 我的api渠道4o 1分(CNY) 1k token，应该比每月20$便宜，就是语音对话没有解决，是不是靠prompt可以实现Writing Mentor的体验，就是speak赶不上
> > 
> > 
> > Writing 和 Reading 可以直接用 Prompt 实现，语音不行。以及马上实时语音对话就要来了（希望 8 月能够被灰度到 = =！），开 ChatGPT Plus 还是值得的。
> 
> 那Writing 和 Reading 的 Prompt 能分享一下嘛，国产的海螺ai好像语音不错，能力怎么样还没试，抽题是部署在cf上面嘛，这个能不能通过大段prompt实现，或者自行部署啥的，感觉公用还是不稳定，要请求几次

https://hubeiqiao.notion.site/ChatGPT-d9336f61a18f48aebbb9dd23d39bc326 里面有。

**Comment by baizhougod** [comment]
> > > > > 如果涉及到语音交互，至少目前还是不一样的。要实现类似 ChatGPT 的语音交互还是需要耗费大量资源的。
> > > > 
> > > > 
> > > > 我的api渠道4o 1分(CNY) 1k token，应该比每月20$便宜，就是语音对话没有解决，是不是靠prompt可以实现Writing Mentor的体验，就是speak赶不上
> > > 
> > > 
> > > Writing 和 Reading 可以直接用 Prompt 实现，语音不行。以及马上实时语音对话就要来了（希望 8 月能够被灰度到 = =！），开 ChatGPT Plus 还是值得的。
> > 
> > 
> > > > > 如果涉及到语音交互，至少目前还是不一样的。要实现类似 ChatGPT 的语音交互还是需要耗费大量资源的。
> > > > 
> > > > 
> > > > 我的api渠道4o 1分(CNY) 1k token，应该比每月20$便宜，就是语音对话没有解决，是不是靠prompt可以实现Writing Mentor的体验，就是speak赶不上
> > > 
> > > 
> > > Writing 和 Reading 可以直接用 Prompt 实现，语音不行。以及马上实时语音对话就要来了（希望 8 月能够被灰度到 = =！），开 ChatGPT Plus 还是值得的。
> > 
> > 
> > 那Writing 和 Reading 的 Prompt 能分享一下嘛，国产的海螺ai好像语音不错，能力怎么样还没试，抽题是部署在cf上面嘛，这个能不能通过大段prompt实现，或者自行部署啥的，感觉公用还是不稳定，要请求几次
> 
> https://hubeiqiao.notion.site/ChatGPT-d9336f61a18f48aebbb9dd23d39bc326 里面有。

好的谢谢我试一下
