### ISSUE TITLE
支持 ChatGPT 的新语音模式

### ISSUE THREAD

**Issue by icrazt** [hubeiqiao/IELTS-Speaking-Simulator#8]
近期 ChatGPT 已经推出了新的语音模式，但尝试时会发现无法在这个 GPT 使用，请问是否可以支持一下？

**Comment by hubeiqiao** [comment]
目前 GPTs 不支持新的实时语音模式，具体有待于 OpenAI。以及 Real-time API 目前很贵，估计得到明年了。今年要是有时间，我打算自己弄一个用 API 的 Demo 看看。
